export const SIGNIN_EMAIL = 'SIGNIN_EMAIL';
export const SIGNIN_EMAIL_ERROR = 'SIGNIN_EMAIL_ERROR';
export const SIGNIN_PASSWORD = 'SIGNIN_PASSWORD';
export const SIGNIN_PASSWORD_ERROR = 'SIGNIN_PASSWORD_ERROR';
export const KEEP_ME_SIGNED_IN = 'KEEP_ME_SIGNED_IN';